package tri_lion.health.service.auth;
import io.jsonwebtoken.Claims; import java.time.*; import java.util.UUID; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import tri_lion.health.domain.user.*; import tri_lion.health.exception.ApiException; import tri_lion.health.external.oauth.GoogleIdTokenVerifier; import tri_lion.health.repository.user.UserRepositories; import tri_lion.health.security.JwtService;
@Service public class AuthService {private final UserRepositories.Users users;private final UserRepositories.RefreshSessions sessions;private final GoogleIdTokenVerifier verifier;private final JwtService jwt;public AuthService(UserRepositories.Users u,UserRepositories.RefreshSessions s,GoogleIdTokenVerifier v,JwtService j){users=u;sessions=s;verifier=v;jwt=j;}
 @Transactional public Login login(String token,String device){var g=verifier.verify(token);var found=users.findByGoogleUserId(g.sub());boolean fresh=found.isEmpty();User u=found.orElseGet(()->users.save(new User(g.sub(),g.email(),g.name(),g.picture())));if(u.getStatus()==User.Status.WITHDRAWN||u.getStatus()==User.Status.SUSPENDED)throw ApiException.forbidden("로그인할 수 없는 계정입니다.");Tokens t=issue(u,device);return new Login(u,t,fresh);}
 @Transactional public Tokens refresh(String raw,String device){if(raw==null)throw new ApiException(HttpStatus.UNAUTHORIZED,"Refresh Token이 필요합니다.");Claims c;try{c=jwt.parse(raw);}catch(Exception e){throw new ApiException(HttpStatus.UNAUTHORIZED,"Refresh Token이 유효하지 않습니다.");}if(!"refresh".equals(c.get("type")))throw new ApiException(HttpStatus.UNAUTHORIZED,"Refresh Token이 유효하지 않습니다.");RefreshSession old=sessions.findByTokenHash(jwt.hash(raw)).filter(RefreshSession::usable).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"Refresh Token이 유효하지 않습니다."));old.revoke();User u=users.findById(old.getUserId()).orElseThrow();return issue(u,device);}
 @Transactional public void logout(String raw){if(raw!=null)sessions.findByTokenHash(jwt.hash(raw)).ifPresent(RefreshSession::revoke);}
 private Tokens issue(User u,String device){String id=UUID.randomUUID().toString();String refresh=jwt.refresh(id,u.getId());sessions.save(new RefreshSession(id,u.getId(),jwt.hash(refresh),Instant.now().plusSeconds(jwt.refreshSeconds()),device));return new Tokens(jwt.access(u.getId(),u.getRole().name(),u.getStatus().name()),refresh,jwt.accessSeconds(),jwt.refreshSeconds());}
 public record Tokens(String access,String refresh,long accessSeconds,long refreshSeconds){} public record Login(User user,Tokens tokens,boolean fresh){}
}
